### ISSUE TITLE
Rewrite the Macros, A Practical Introduction

### ISSUE THREAD

**Issue by Veykril** [Veykril/tlborm#7]
as it uses an invalid matcher sequence, an expr fragment followed by `...`, this was okay in Rust 1.0 til 1.7, in which it became a warning until finally being turned into a hard error in Rust 1.11.

**Comment by tranzystorek-io** [comment]
In the `a[n] = $($inits:expr),+ , ... , $recur:expr` the `, ... ,` is not a problem because of disallowed tokens (the `,` immediately follows the `$($inits:expr),+`, which is fine), but because of ambiguity.

The most "true to the old look" form I've found is `a[n] = $($inits:expr),+ ; ... ; $recur:expr`, e.g. `a[n] = 0, 1; ...; a[n-1] + a[n-2]`.
Here's a working example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e62d3a36b7818742369ddae9291a07da

**Comment by Veykril** [comment]
Delimiting the triple dots with semicolons seems like a great choice! Definitely a lot better than just using `=>`.

**Comment by tranzystorek-io** [comment]
After a more thorough read I noticed that the chapter actually builds up to the explanation about the `,` after `expr`s as well as the ambiguity of `$(inits:expr),+ , ... ,`. We could still replace the `=>` form in the middle with `; ... ;` I guess...

**Comment by Veykril** [comment]
Oh ye, I meant to answer that part as well whoops. As you just noticed the comma isn't the sole problem ye ... Its due to rust accepting `...` after expression fragments at first back when the book was written. Replacing `=>` with `; ... ;` definitely looks better in my opinion as `=>` looks really arbitrary otherwise.
