### ISSUE TITLE
Correction: Parsing function

### ISSUE THREAD

**Issue by saona-raimundo** [Veykril/tlborm#71]
First of all, thanks for the little book! I am enjoying the reading!

In [Parsing Rust - Fucntion](https://veykril.github.io/tlborm/decl-macros/building-blocks/parsing.html#function) section, I think the optional `async` keyword is missing.

How should one match the `async` keyword?

**Comment by Veykril** [comment]
That section deliberately skips over qualifiers and generics, you can optionally match the async keyword by `$(async)?`, but you can't expand it since there is no meta variable matcher. So you'd unfortunately have to duplicate the entire macro arm for async vs non-async if youwant to specialize on async functions
